config/routes.rb
Rails.application.routes.draw do
  
  resources :products do
    collection { post :import }
  end


  resources :contacts
  get 'flex/flexbox'

  get 'design/index'

  get 'design/home'

  get 'design/parallax'

  get 'design/jquery'

  get 'design/css'

  get 'design/images'

  get 'design/clock'

  get 'design/buttons'

  get 'design/navbar'

  get 'design/footers'

  get 'design/forms'

  get 'design/cssgrid'

  get 'design/bootstrap'

  get 'design/flexbox'


  root to: 'design#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

 before_save do |contact|
    contact.last = contact.last.titleize
    contact.first = contact.first.titleize
    contact.model = contact.model.upcase
  end

 


end

app/models/product.rb
class Product < ApplicationRecord



    def self.to_csv(options = {})

      attributes = %w{id title price description sale_price image discount other}

        CSV.generate(headers: true) do |csv|
          csv << attributes

          all.each do |product|
            csv << product.attributes.values_at(*attributes)
        end
          end
    end





    def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
        product = find_by_id(row['id']) || new
        product.attributes = row.to_hash
        product.save!
      end
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    # phone element used to test date
    @contact.phone= Date.new params[:contact]['phone(1i)'].to_i, params[:contact]['phone(2i)'].to_i, params[:contact]['phone(3i)'].to_i
    


    respond_to do |format|
      if @contact.save

        message = " '#{@contact.first}' has requested you to contact them, They're interested in a '#{@contact.model}' Call '#{@contact.phone}' "
        
        TwilioTextMessenger.new(message).sales
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end 

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first, :last, :model, :phone, :date)
    end
end

app/controllers/design_controller.rb
class DesignController < ApplicationController
  

  def index
  end

  def home
  end

  def parallax
  end

  def jquery
  end

  def css
  end

  def images
  end

  def clock
  end

  def buttons
  end

  def navbar
  end

  def footers
  end

  def forms
  end

  def cssgrid
  end

  def bootstrap
  end

 
end

app/controllers/flex_controller.rb
class FlexController < ApplicationController
  




  def flexbox
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all


    respond_to do |format|
      format.html
      format.csv{ send_data @products.to_csv }
      format.xls #{ send_data @products.to_csv(col_sep: "\t") }
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # POST IMPORT
  def import
    Product.import(params[:file])
    redirect_to products_path, notice: "Products Imported Succcessfully"
  end


  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :sale_price, :image, :description, :discount, :other)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/design_helper.rb
module DesignHelper
end

app/helpers/flex_helper.rb
module FlexHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first %>
    <%= form.text_field :first, id: :contact_first %>
  </div>

  <div class="field">
    <%= form.label :last %>
    <%= form.text_field :last, id: :contact_last %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :contact_model %>
  </div>

  <div class="field">
    <%= form.label :phone, "Phone" %>
    <%= form.date_select :phone, id: :contact_phone, :order => [ :month, :day, :year], :start_year=>1950,:end_year=>2018 %>
  </div> 

  <div class="field">
    <%= form.label :date, "Date" %>
    <%= form.text_field :date, id: :contact_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>First</th>
      <th>Last</th>
      <th>Model</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first %></td>
        <td><%= contact.last %></td>
        <td><%= contact.model %></td>
        <td><%= contact.phone %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First:</strong>
  <%= @contact.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @contact.last %>
</p>

<p>
  <strong>Model:</strong>
  <%= @contact.model %>
</p>

<p>
  <strong>Phone:</strong>
  <%=  @contact.phone %>

</p>


<p>
  <strong>Date:</strong>
  <%= @contact.date %>
</p>

<p>
  <strong> Date Input:</strong>
  <%#=  @contact.created_at.in_time_zone("America/Denver") %>
  <%= @contact.created_at.strftime("%m-%d-%Y") %>
</p>

<p>
  <strong> Time Input:</strong>
  <%#=  @contact.created_at.in_time_zone("America/Denver") %>
  <%= @contact.created_at.strftime(" %T") %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/design/bootstrap.html.erb
<h1>Design#bootstrap</h1>
Test here

app/views/design/buttons.html.erb
<h1>Design#buttons</h1>
<p>Find me in app/views/design/buttons.html.erb</p>

app/views/design/clock.html.erb
<h1>Design#clock</h1>
<p>Find me in app/views/design/clock.html.erb</p>

app/views/design/css.html.erb
<style>


    /* font-family: 'Roboto', sans-serif;

    font-family: 'Open Sans', sans-serif;

    font-family: 'Lato', sans-serif;

    font-family: 'Montserrat', sans-serif;

    font-family: 'Play', sans-serif; */


* {
  box-sizing: border-box;
}
body{
    background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/wallpaper_carbon_fiber.jpg");
    
}
.item {
  width: 200px;
  height: 200px;
  margin: 50px auto;
  padding-top: 75px;
  background: pink;
  text-align: center;
  color: white;
  font-size: 3em;
  box-shadow:  grey 1px 1px 10px;
}

.item1 {
  width: 200px;
  height: 200px;
  margin: 50px auto;
  padding-top: 75px;
  background: pink;
  text-align: center;
  color: white;
  font-size: 3em;
  
 
}

.background-img{
    background-color:grey;
    width:400px;
    height:200px;
    border-radius: 7px;
}


.grid2{
  display:grid;
  grid-template-columns: 1fr 1fr;
  height:100px;
  font-size: 18pt;
  background-color:pink;
  border-radius: 7px;

}


.box1{
display:grid;
background-color: grey;
color:red;
justify-content: right;
align-items: center;
padding:15px;
border-radius: 8px 0px 0px 8px;

}


.box2{
  display:grid;
  background-color:red;
  border-left:2px solid white;
  color:grey;
  justify-content: left;
  align-items: center;
  padding:15px;
  border-radius: 0px 8px 8px 0px;

}



.grid3{
  display:grid;
  grid-template-columns: 1fr 1fr;
  height:100px;
  font-size: 18pt;
  background-color:gainsboro;
  border-radius: 7px;
    background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/Preview_01.jpg");


}


.box4{
display:grid;
color:white;
justify-content: right;
align-items: center;
padding:4px;


}


.box5{
  display:grid;
  color:white;
  justify-content: left;
  align-items: center;
  padding:4px;
  

}

.grid5{
  display:grid;
  justify-content: center;
  grid-gap:20px;
  font-size: 13pt;
  color:white;
  text-align: center;
  grid-template-columns: 1fr 4fr 1fr;
  grid-template-rows: 100px 
                      100px 
                      100px 
                      100px 
                      100px 
                      80px ;
  grid-template-areas:
  "content content sidebar-e"
  "content content sidebar-b"
  "content content sidebar-c"
  "content content sidebar-d"
  "content content sidebar-a"
  "footer footer footer"
}


.gr5item{
  display:grid;
  background:yellow;
  padding:15px;
  border: 3px solid white;
  border-radius: 6px;


}
.g5content{
  display:grid;
  background:blue;
  font-size:4vw;
  line-height:1.1;
  padding:15px;
  grid-area: content;
  border: 3px solid white;
  border-radius: 6px;
  background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/Preview_01.jpg");
}


.gsidebar-a{
  display:grid;
  background:yellow;
  grid-area: sidebar-a;
  background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/Preview_02.jpg");
}


.gsidebar-b{
  display:grid;
  background:purple;
  grid-area: sidebar-b;
}


.gsidebar-c{
  display:grid;
  background:brown;
  grid-area: sidebar-c;
  background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/Preview_03.jpg");
}


.gsidebar-d{
  display:grid;
  background:green;
  grid-area: sidebar-d;
}

.gsidebar-e{
    display:grid;
  background:pink;
  grid-area: sidebar-e;
  background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/Preview_04.jpg");
}
.gsidebar-e:hover{
    color: red;
     border: 3px solid red;
     background: white;
}


.g5footer{
  display:grid;
  background:blue;
   padding:15px;
  grid-area: footer;
  border: 3px solid white;
  border-radius: 6px;

}

.forest{
    display:grid;
    background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/static1.squarespace.jpg");
    width: 80%;
    background-size:cover;
      max-width: 950px;
      line-height: 1.3;
     justify-content: center;
    font-size:28pt;
    font-family: 'Play', sans-serif; 
    color:white;
    height: 550px;
    grid-gap:15px;
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
    grid-template-rows: 100px 
                        100px 
                        100px 
                        100px
                        100px
 ;
  grid-template-areas:
 " .  title title title  . "
   " .  .  .  .  . "
   " .  atv1 . atv2 . "
  " .  .  .  . . "
  " .  .  .  .  . " ;

}
.forest-title{
grid-area: title;
   align-self: center;
  justify-self: center;


}


.atv1 {
     grid-area: atv1;
     width:50px
  
}


.atv2 {
     grid-area: atv2;
    
}

/* Media Queries */


@media (max-width: 760px) {
  body {
    background-color: lightblue;
}


.grid5{
  display:grid;
  justify-content: center;
  grid-gap:10px;
  font-size: 11pt;
  color:white;
  text-align: center;
  grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
  grid-template-rows: 
                      300px 
                      90px 
                       ;
  grid-template-areas:
  "content     content   content    content   content"
  "sidebar-a  sidebar-b sidebar-c sidebar-d sidebar-e"
  "footer       footer    footer    footer     footer"

}
}

@media (max-width: 600px) {
  body {
    background-color: yellowgreen;
    margin: 10px;
}

.grid5{
  display:grid;
  justify-content: center;
  grid-gap:10px;
  font-size: 11pt;
  color:white;
  text-align: center;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: 
                      auto
                      70px 
                      70px
                      70px
                    
                  ;
  grid-template-areas:
  "content   content"
  "sidebar-a  sidebar-c" 
  "sidebar-b  sidebar-d"
  "sidebar-e  sidebar-e"
  "footer     footer"
}


.forest{
    display:grid;
    background:url("https://s3-us-west-2.amazonaws.com/factory-circuit-mont/static1.squarespace.jpg");
    width: 100%;
     justify-content: center;
    background-size:cover;
    font-size:18pt;
    font-family: 'Play', sans-serif; 
    color:white;
    height: 400px;
    grid-column-gap:10px;
    grid-row-gap:15px;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr
                        1fr
                        1fr
                        1fr
                        1fr
 ;
  grid-template-areas:
  "  title title title  "
  "  .  .  . "
  " .  .  .  "
   "  . atv1  . " 
   " .  .  .  ";

}
.forest-title{
grid-area: title;
padding-top:20px;
}


.atv1 {
     grid-area: atv1;
    
}



}


/* takes away second atv at 850px and under*/

@media (max-width: 850px) {

.atv2 {
     grid-area: atv2;
     display:none
}

}



</style>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


<div class="item" data-aos="fade-down">1</div>
<div class="item" data-aos="fade-up">2</div>
<div class="item" data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-in-out-quart" > 3


</div>



<div class="item" data-aos="fade-left">4</div>

<div class="item" data-aos="zoom-in">5</div>
<div class="item" data-aos="zoom-out">6</div>

<div class="item" data-aos="slide-up">7</div>

<div class="item" data-aos="flip-up">8</div>
<div class="item" data-aos="flip-down">9</div>
<div class="item" data-aos="flip-right">10</div>
<div class="item" data-aos="flip-left">11</div>

<div class="item" data-aos="fade-up-right">12</div>

<div class="item" data-aos="fade-up-left">13</div>

<div class="item" data-aos="zoom-in-up">14</div>

<div class="item" data-aos="zoom-in-left">15</div>

<div class="item" data-aos="fade-down"
                  data-aos-easing="linear"
                  data-aos-offset="500"
                  data-aos-duration="1000">16</div>


<div 
     class="item"
     data-aos="fade-down-right"
     data-aos-easing="ease-out-cubic"
     data-aos-offset="500"
     data-aos-duration="500">
     17
</div>
     
   
<center>


<div class="item1"
     data-aos="slide-right"
     data-aos-easing="ease-out-cubic"
     data-aos-duration="1300">
     18
</div>
</div>
<center>


<br>
<br>
<hr>
<div class ="grid2">

        <div class= "box1" data-aos="slide-right" data-aos-offset="200" data-aos-easing="ease-in-out-quart"data-aos-duration="1200" >
            REGISTER
        </div>

        <div class = "box2" data-aos="slide-left" data-aos-offset="200" data-aos-easing="ease-in-out-quart"data-aos-duration="1200" >
            NOW
        </div>
 
</div>

<hr>
<hr>
<div class ="grid3">

        <div class= "box4" data-aos="slide-right" data-aos-offset="200" data-aos-easing="ease-in-out-quart"data-aos-duration="1200" >
            FLOATING TEXT
        </div>

        <div class = "box5" data-aos="slide-left" data-aos-offset="200" data-aos-easing="ease-in-out-quart"data-aos-duration="1200" >
            CARBON BACKGROUND
        </div>
 
</div>

<hr>

GRID 5
<br>
<br>

<div class= "grid5" >
  


 <div class= "g5content">
  main content fixed area with lots of words for wrapping text and informational purposes. Text is also resposnive using the vw font sizing property.  Using line height was necessary to make the lines properly fit.
  </div>

   <div class= "gsidebar-a  gr5item"  >
  sidebar a
  </div>

   <div class= "gsidebar-b gr5item" >
  sidebar b
  </div>

   <div class= "gsidebar-c gr5item" >
  sidebar c
  </div>

   <div class= "gsidebar-d gr5item" >
  sidebar d
  </div>

  <div class= "gsidebar-e gr5item"  >
  sidebar e
  </div>

   <div class= "g5footer">
  footer
  </div>
</div>
<br>
<br>

<hr>


GRID 5
<br>
<br>

<div class= "grid5" data-aos="fade-down"
                  data-aos-easing="linear"
                  data-aos-offset="100"
                  data-aos-duration="1000">
  


 <div class= "g5content" data-aos="fade-left" data-aos-offset="270" data-aos-easing="ease-in-out-quart">
  main content fixed area adasdfasd asdfsadfas  asdfsadf asdfsadf  asdfsadfa adfsadf asfsadfas sdfsadf 
  </div>

   <div class= "gsidebar-a  gr5item" data-aos="slide-right" data-aos-offset="270" data-aos-easing="ease-in-out-quart" >
  sidebar a
  </div>

   <div class= "gsidebar-b gr5item" data-aos="fade-right" data-aos-offset="270" data-aos-easing="ease-in-out-quart" >
  sidebar b
  </div>

   <div class= "gsidebar-c gr5item" data-aos="slide-left"  data-aos-offset="270" data-aos-easing="ease-in-out-quart" >
  sidebar c
  </div>

   <div class= "gsidebar-d gr5item" data-aos="fade-right" data-aos-offset="270" data-aos-easing="ease-in-out-quart" >
  sidebar d
  </div>

  <div class= "gsidebar-e gr5item" data-aos="fade-right" data-aos-offset="270" data-aos-easing="ease-in-out-quart" >
  sidebar e
  </div>

   <div class= "g5footer" data-aos="fade-left" data-aos-offset="270" data-aos-easing="ease-in-out-quart">
  footer
  </div>
</div>
<hr>
<hr>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class ='forest'>
    <div class = "forest-title" data-aos="fade-up">
    Come play in our world!
    </div>
    <div class= "atv1" data-aos="fade-right" data-aos-offset="80" data-aos-easing="ease-in-out-quart" data-aos-duration="1000" >
    <img src= "https://s3-us-west-2.amazonaws.com/factory-circuit-mont/camogrizzlyright.png" style="width:225px">
    </div>
    <div class= "atv2" data-aos="fade-left" data-aos-offset="150" data-aos-easing="ease-in-out-quart"data-aos-duration="1000" >
    <img src= "https://s3-us-west-2.amazonaws.com/factory-circuit-mont/wolverine+white_edited-1.png" style="width:325px" >
    </div>
</div>


<br>

 
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/design/footers.html.erb
<h1>Design#footers</h1>
<p>Find me in app/views/design/footers.html.erb</p>

app/views/design/forms.html.erb
<h1>Design#forms</h1>
<p>Find me in app/views/design/forms.html.erb</p>

app/views/design/home.html.erb
Home page

<br>

app/views/design/images.html.erb
<h1>Design#images</h1>
<p>Find me in app/views/design/images.html.erb</p>

app/views/design/index.html.erb
<h1>Design#index</h1>
<p>Find me in app/views/design/index.html.erb</p>

<h2>  Here is my cool website </h2>

<h2>  do you like it? </h2>

app/views/design/jquery.html.erb
<h1>Design#jquery</h1>
<p>Find me in app/views/design/jquery.html.erb</p>

app/views/design/navbar.html.erb
<h1>Design#navbar</h1>
<p>Find me in app/views/design/navbar.html.erb</p>

app/views/flex/flexbox.html.erb
<body>
    <div id="left" class="column">
        <div class="top-left">Hello TOP LEFT</div>
        <div class="bottom"> BOTTOM LEFT</div>
    </div>
    <div id="right" class="column">
        <div class="top-right">TOP RIGHT</div>
        <div class="bottom">BOTTOM RIGHT</div>
    </div>
</body>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div style="background-color:#f6f6f6">
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Price</th>
      <th>Sale price</th>
      <th>Image</th>
      <th>Description</th>
      <th>Discount</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.sale_price %></td>
        <td><%= product.image %></td>
        <td><%= product.description %></td>
        <td><%= product.discount %></td>
        <td><%= product.other %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<hr>
<h3> Export Products via CSV & XLS</h3>
<br>


 <button >
<%= link_to "Download Products to CSV ", products_path(format: "csv") %>
</button>
  <br>
  <br> 
  <button> 
<%= link_to "Download Products to XLS", products_path(format: "xls") %>
</button>

<br> 
<hr>
<!-- Import CSV -->

<h3> Import Products via CSV </h3>
<br>

<%= form_tag import_products_path,  multipart: true do %>

<%= file_field_tag :file %>

<br>
<br>

<%= submit_tag "Import CSV"%>

<%end%>

<br>
<hr>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @product.sale_price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @product.discount %>
</p>

<p>
  <strong>Other:</strong>
  <%= @product.other %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_nav.html.erb
<!-- Navbar -->

  <%= link_to "Index",design_index_path %>

  <%= link_to "Home", design_home_path %>

  <%= link_to "Parallax", design_parallax_path %>

  <%= link_to "JQuery", design_jquery_path %>

  <%= link_to "CSS", design_css_path %>

  <%= link_to "Images", design_images_path %>

  <%= link_to "Clock", design_clock_path %>

  <%= link_to "Buttons", design_buttons_path %>

  <%= link_to "Navbars", design_navbar_path%>

  <%= link_to "Footers", design_footers_path %>

  <%= link_to "Forms", design_forms_path %>

  <%= link_to "CSS GRID", design_cssgrid_path %>

  <%= link_to "Bootsrap", design_bootstrap_path %>

  <%= link_to "Flexbox", design_flexbox_path %>

 